//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEmployeeViewModel1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeViewModel
    {
        public int EmployeeID { get; set; }
        public string Name { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string Address { get; set; }
        public string DepartmentName { get; set; }
        public string Remember { get; set; }
    }
}
